# Site settings
name: Vasudev Sharma
title: Vasudev Sharma | Computer Vision and Deep Learning Research Aspirant
description: Passionate Research asspirant whose interest lies in computer vision and deep learning
url: https://vs74.github.io/
baseurl: ''
email: vasudevsharma74@yahoo.com
cover: https://vs74.github.io/img/og.png
logo: https://vs74.github.io/img/emojis/technologist.png
resume: https://vs74.github.io/resume.pdf
social:
  - title: email
    url: mailto:vasudevsharma74@yahoo.com
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=lC6m1coAAAAJ&hl=en
  - title: Research Gate
    url: https://www.researchgate.net/profile/Vasudev_Sharma2
  - title: github
    url: https://github.com/vs74
  - title: linkedin
    url: https://www.linkedin.com/in/vs74

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
